language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew

stages:
- name: build
- name: release
  # only publish releases from "release" branch and not in pull requests
  if: branch = master AND type IN (push)

jobs:
  include:
  # run gradle build
  - stage: build
    script: ./gradlew build
  # release a new stable version to bintray
  - stage: release
    script: ./gradlew bintrayUpload -x test -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER