name: Publish package
on:
  workflow_dispatch:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for deploy.sh
        run: chmod +x .build/deploy.sh
      - name: Publish release
        run: .build/deploy.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
